#!/bin/bash
## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
SETUP_DIR=${PROJ_DIR}/.setup;
CONF_DIR=${PROJ_DIR}/conf.d;

## constants
OUTPUT_FILE="${SETUP_DIR}/build.Version";

## processing
BUILD_VERSION=$(${CURR_DIR}/../versioning/get-next -i -q);

## output
printf "$BUILD_VERSION" > "${OUTPUT_FILE}";
printf "$BUILD_VERSION";
