#!/bin/bash
# assumes v2 api
## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
SETUP_DIR=${PROJ_DIR}/.setup;
CONF_DIR=${PROJ_DIR}/conf.d;

## constants
CONF_FILE_PATH="${CONF_DIR}/DOCKER_HUB_TOKEN";
DOCKER_HUB_URL=$(${CURR_DIR}/docker_hub_url);
OUTPUT_FILE="${SETUP_DIR}/docker_hub.Token";

## processing
DOCKER_HUB_TOKEN=0;
__exists=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then DOCKER_HUB_TOKEN=$(cat ${CONF_FILE_PATH}); fi;
if [[ ${DOCKER_HUB_TOKEN} = '0' ]]; then
  if [[ ${DOCKER_HUB_USERNAME} = "" ]] || [[ ${DOCKER_HUB_PASSWORD} = "" ]]; then
    printf "\n\033[31m[ERR] ${CONF_FILE_PATH} did not exist. Unable to retrieve authorisation token for authenticating with the Docker Registry API.\033[0m\n";
    printf "\n\033[31m\tDefine \033[1m\$DOCKER_HUB_USERNAME\033[0m\033[31m and \033[1m\$DOCKER_HUB_PASSWORD\033[0m\033[31m environment variables so we can do the authentication! \033[0m\n\n";
    exit 1;
  else
    DOCKER_HUB_TOKEN=$(
      curl -sSlfa -H "Content-Type: application/json" -d "{\"username\":\"${DOCKER_HUB_USERNAME}\",\"password\":\"${DOCKER_HUB_PASSWORD}\"}" \
        -X POST "${DOCKER_HUB_URL}/v2/users/login" |
        cut -f 4 -d "\""
    );
  fi;
fi;

## output
printf "$DOCKER_HUB_TOKEN" > "${OUTPUT_FILE}";
printf "$DOCKER_HUB_TOKEN";
