#!/bin/bash
## template
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
SETUP_DIR=${PROJ_DIR}/.setup;
CONF_DIR=${PROJ_DIR}/conf.d;

## constants
CONF_FILE_PATH="${CONF_DIR}/REPOSITORY_NAME";
OUTPUT_FILE="${SETUP_DIR}/repository.Name";

## processing
REPOSITORY_NAME='zephinzer/alpine-node-gitbook'
__exists=$(stat ${CONF_FILE_PATH} &>/dev/null);
if [[ $? = "0" ]]; then REPOSITORY_NAME=$(cat ${CONF_FILE_PATH}); fi;

## output
printf "$REPOSITORY_NAME" > "${OUTPUT_FILE}";
printf "$REPOSITORY_NAME";
