version: "3"
services:
  gitbook:
    image: zephinzer/alpine-node-gitbook:latest
    container_name: alpine-node-gitbook-with-docker-compose
    working_dir: /app
    entrypoint:
      - "gitbook"
      - "serve"
    expose:
      - "4000/tcp"
    ports:
      - "80:4000"
    volumes:
      - ./:/app