#!/bin/bash
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;

${CURR_DIR}/../build/setup;
docker build -t ${DOCKER_TEMP_TAG} -f "${PROJ_DIR}/Dockerfile" "${PROJ_DIR}";
${CURR_DIR}/../build/teardown;