#!/bin/bash
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
SETUP_DIR=${PROJ_DIR}/.setup;

${CURR_DIR}/../build/setup;
DOCKER_TEMP_TAG="$(cat ${SETUP_DIR}/docker_temp.Tag)";
docker build -f ${PROJ_DIR}/Dockerfile "${PROJ_DIR}" -t ${DOCKER_TEMP_TAG};
CONTAINER_INFO="$(docker run ${DOCKER_TEMP_TAG})";
NODE_VERSION="$(echo "${CONTAINER_INFO}" | grep 'NODE' | cut -f 2 -d ':')";
YARN_VERSION="$(echo "${CONTAINER_INFO}" | grep 'YARN' | cut -f 2 -d ':')";
GITBOOK_VERSION="$(echo "${CONTAINER_INFO}" | grep 'GITBOOK' | cut -f 2 -d ':')";
EXISTENCE_TAG="node-${NODE_VERSION}_yarn-${YARN_VERSION}_gitbook-${GITBOOK_VERSION}";
docker login -u  $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD;
docker tag next_alpine_node_gitbook   ${DOCKER_REPO}:${GITBOOK_VERSION};
docker push                           ${DOCKER_REPO}:${GITBOOK_VERSION};
docker tag next_alpine_node_gitbook   ${DOCKER_REPO}:${EXISTENCE_TAG};
docker push                           ${DOCKER_REPO}:${EXISTENCE_TAG};
docker tag next_alpine_node_gitbook   latest;
docker push                           latest;
docker logout
${CURR_DIR}/../build/teardown;
