#!/bin/bash
CURR_DIR=$(dirname $0);
PROJ_DIR=${CURR_DIR}/../..;
CONF_DIR=${PROJ_DIR}/conf.d;
SETUP_DIR=${PROJ_DIR}/.setup;

CONTAINER_INFO="$(docker run ${DOCKER_TEMP_TAG})";
NODE_VERSION="$(printf "${CONTAINER_INFO}" | grep 'NODE' | cut -f 3 -d ' ')";
YARN_VERSION="$(printf "${CONTAINER_INFO}" | grep 'YARN' | cut -f 3 -d ' ')";
GITBOOK_VERSION="$(printf "${CONTAINER_INFO}" | grep 'GITBOOK' | cut -f 3 -d ' ')";
EXISTENCE_TAG="node-${NODE_VERSION}_yarn-${YARN_VERSION}_gitbook-${GITBOOK_VERSION}";
docker login -u  $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD;
docker tag next_alpine_node_gitbook   ${DOCKER_REPO}:${GITBOOK_VERSION};
docker push                           ${DOCKER_REPO}:${GITBOOK_VERSION};
docker tag next_alpine_node_gitbook   ${DOCKER_REPO}:${EXISTENCE_TAG};
docker push                           ${DOCKER_REPO}:${EXISTENCE_TAG};
docker tag next_alpine_node_gitbook   latest;
docker push                           latest;
docker logout